apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-distribution-vllm
spec:
  replicas: 1
  server:
    distribution:
      name: starter
    containerSpec:
      env:
      - name: VLLM_URL
        value: "https://litellm-prod.apps.maas.redhatworkshops.io/v1"
      - name: VLLM_API_TOKEN
        value: "sk-M1BNtjw6bppawN5N7vg3tA"
    storage:
      size: "20Gi"
      mountPath: "/home/lls/.lls"
